[bumpver]
current_version = "2.4.3"
version_pattern = "MAJOR.MINOR.PATCH"
commit = true
tag = true

[bumpver.file_patterns]
"setup.py" = [
    'version="{version}"',
]

"bumpver.toml" = [
    'current_version = "{version}"'
]

"qalib/__init__.py" = [
    '__version__ = "{version}"'
]

"pyproject.toml" = [
    'version = "{version}"'
]

"docs/usage/installation.md" = [
    '>>> {version}'
]