[bumpver]
current_version = "1.0.1"
version_pattern = "MAJOR.MINOR.PATCH"
commit = true
push = true
tag = true

[bumpver.file_patterns]
"setup.py" = [
    'version="{version}"',
]

"bumpver.toml" = [
    'current_version = "{version}"'
]

"qalib/__init__.py" = [
    '__version__ = "{version}"'
]

"docs/usage/installation.md" = [
    '>>> {version}'
]