name: Code Coverage

on:
  push:
    branches: '**'

  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Discord-Qalib
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest pytest-cov typing_extensions
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests and collect coverage
        run: pytest --cov=./ --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
